### ISSUE TITLE
Example needs rework.

### ISSUE THREAD

**Issue by joannesalfa** [AirConsole/airconsole-construct2#1]
I've followed this guide

http://developers.airconsole.com/#/guides/construct2

I added extra console logs to appear "Moved" if you pressed button in your device.

I tried to rename index.html to screen.html then created controller.html, now uploaded at my server.

Then I ran with http://www.airconsole.com/#http://powerupware.com/airconsole/

I pressed  button "Move" many times on my nexus 7 and the screen, a blue square won't move anymore.

I think this example needs rework

**Comment by joannesalfa** [comment]
For further details

http://www.airconsole.com/simulator/#debug:http://powerupware.com/airconsole/

Try with 2 controllers, when you press "Move" button they won't move in the screen.

It seems  On receive message data is broken, not sure how it happened.

**Comment by francois-dibulo** [comment]
Thank you - I will have a look at it!

**Comment by francois-dibulo** [comment]
I had a look at your http://powerupware.com/airconsole/controller.html and it is missing the handshake, which is necessary when building a game with construct2 and AirConsole.

Its described here:
http://developers.airconsole.com/#/guides/construct2

``` javascript
 //....

  var handshake = function() {
     air_console.message(AirConsole.SCREEN, {
         handshake: true
      });
  };

  air_console.onReady = function() {
    handshake();
  };

 air_console.onMessage(function(device_id, data) {
    if (data.handshake) {
        handshake();
    }
  });
```

This is basically doing something like "Hello Screen I am here"
