### ISSUE TITLE
Suggestion: can create a controller.html in Construct 2

### ISSUE THREAD

**Issue by danimesq** [AirConsole/airconsole-construct2#14]

**Comment by Psychokiller1888** [comment]
Was working on that a while ago but I did not finish it. Will see if I can get to a working state

**Comment by danimesq** [comment]
I have a suggestion: a exporter for Contruct 2 that will help the AirConsole controller plugin by exporting the index.html as controller.html, creating a folder with all other files and then point controller.html for load resources from this folder in the root directory.

**Comment by Psychokiller1888** [comment]
This is now made by X3M, please visit his topic on scirra.com: https://www.scirra.com/forum/viewtopic.php?f=153&t=186227

**Comment by danimesq** [comment]
Thanks!
