### ISSUE TITLE
Cannot load

### ISSUE THREAD

**Issue by Raiper34** [AirConsole/airconsole-construct2#2]
When I try install addon using .c2addon i get follwing message
"Cannot load .c2addon file: info.xml is missing from the root"

**Comment by francois-dibulo** [comment]
Thanks for your message!

I am looking at it right now!

In the meantime if you want you can just rename the c2addon file to .zip and extract the files into:

`YOUR_CONSTRUCT2_PATH/exporters/html5/plugins/airconsole/`

**Comment by francois-dibulo** [comment]
UPDATE:

its fixed now! Please download the airconsole.c2addon again and let me know if there are any problems!
