### ISSUE TITLE
Exposed parameters creating unneeded confusion?

### ISSUE THREAD

**Issue by ghost** [AirConsole/airconsole-construct2#3]
This is less an issue and more of a possible enhancement, I think, though I may be misunderstanding something.

At the very end of the tutorial, there's this line:

> Note that only the "Value" value is something you should hard code. All other values can be found in the expression window:

Is there a reason these values that don't need to be "hard coded" are exposed? Like, is there ever a situation where I might want to put something other than "AirConsole.Message" in the "Message" field, for example? If not, I think I would be a bit less confused if these fields were hidden away entirely.

**Comment by francois-dibulo** [comment]
You are right, we can hide some of the fields and it does not make sense to expose them. Good input! :) Will be updated in the next commit. Thanks!
