### ISSUE TITLE
Update API to latest version

### ISSUE THREAD

**Issue by ghost** [AirConsole/airconsole-construct2#4]
I'm trying to work on a project with this plugin and I'm getting the "Please update API to version 1.3.0" message when testing with the simulator. I've tried changing the references in the exported project to reference the new API but it's still giving me the error (and it's annoying to have to replace the files each export).

**Comment by francois-dibulo** [comment]
Thanks for opening the issue!
I updated the plugin to the latest 1.3.0 AirConsole API version and now the message should not appear anymore after installing the new airconsole.c2addon file.

**Comment by ghost** [comment]
@francois-n-dream Thanks for taking care of that. Could the documentation (http://developers.airconsole.com/#/guides/construct2) be updated as well?

**EDIT:** Also, the c2addon file needs to be fixed, it's missing the "files" folder.
