### ISSUE TITLE
Generated controller doesn't work with Construct 2 build

### ISSUE THREAD

**Issue by ghost** [AirConsole/airconsole-construct2#7]
Generated controllers created with http://developers.airconsole.com/tools/airconsole-controls/ctrl-generator/controller.html don't seem to work properly with Construct 2 builds. At a glance, it seems like they're missing the handshake code, though even slipping that in didn't seem to make my generated controller work so there may be more to it than that.

**Comment by Psychokiller1888** [comment]
That is now solved
